export const demoConfig = {
  webSearch: {
    searchEngines: [
      {name: 'Google', url: ''},
      {name: 'Google Images', url: ''},
      {name: 'Google Maps', url: ''},
      {name: 'Gmail', url: ''},
      {name: 'Google Mail', url: ''},
      {name: 'Google Inbox', url: ''},
      {name: 'Google Drive', url: ''},
      {name: 'Maps', url: ''},
      {name: 'Twitter', url: ''},
      {name: 'Facebook', url: ''},
      {name: 'LinkedIn', url: ''},
      {name: 'Youtube', url: ''},
      {name: 'Wikipedia', url: ''},
      {name: 'Amazon', url: ''},
      {name: 'eBay', url: ''},
      {name: 'IMDb', url: ''},
      {name: 'Rotten Tomatoes', url: ''},
      {name: 'Bing', url: ''},
      {name: 'Yahoo', url: ''},
      {name: 'Ask', url: ''},
      {name: 'Flickr', url: ''},
      {name: 'Wolfram|Alpha', url: ''},
      {name: 'Yubnub', url: ''},
      {name: 'DuckDuckGo', url: ''}
    ]
  },
  applications: {
    searchDirectories: [],
    applications: []
  }
}

export const demoData = {
  music: [
    { name: 'I\'m Good',
      artist: 'The Mowgli\'s',
      album: 'I\'m Good',
      genre: 'Pop' },
    { name: 'Baby Love',
      artist: 'Petite Meller',
      album: 'Baby Love',
      genre: 'Pop' },
    { name: 'T-Shirt Weather',
      artist: 'Circa Waves',
      album: 'T-Shirt Weather',
      genre: 'Pop' },
    { name: 'Fade Out Lines - The Avener Rework',
      artist: 'The Avener & Phoebe Killdeer',
      album: 'Fade Out Lines',
      genre: 'Pop' },
    { name: 'Salt',
      artist: 'Bad Suns',
      album: 'Language & Perspective',
      genre: 'Pop' },
    { name: 'Ship To Wreck',
      artist: 'Florence + The Machine',
      album: 'Ship To Wreck',
      genre: 'Pop' },
    { name: 'Couch Potato',
      artist: 'Shortstraw',
      album: 'Good Morning, Sunshine',
      genre: 'Pop' },
    { name: 'Good Day',
      artist: 'distant cousins',
      album: 'Good Day',
      genre: 'Pop' },
    { name: 'Ex\'s & Oh\'s',
      artist: 'Elle King',
      album: 'Love Stuff',
      genre: 'Pop' },
    { name: 'Irresistible',
      artist: 'Fall Out Boy',
      album: 'American Beauty/American Psycho',
      genre: 'Pop' },
    { name: 'Centuries',
      artist: 'Fall Out Boy',
      album: 'American Beauty/American Psycho',
      genre: 'Pop' },
    { name: 'Light Me Up',
      artist: 'Flyte',
      album: 'Light Me Up',
      genre: 'Pop' },
    { name: 'Violins',
      artist: 'I\'m From Barcelona',
      album: 'Violins',
      genre: 'Pop' },
    { name: 'I Bet My Life',
      artist: 'Imagine Dragons',
      album: 'Smoke + Mirrors (Deluxe)',
      genre: 'Pop' },
    { name: 'RIVA (Restart the Game) - Radio Edit',
      artist: 'Klingande',
      album: 'RIVA (Restart The Game) [Radio Edit]',
      genre: 'Pop' },
    { name: 'Lean On (feat. MØ & DJ Snake)',
      artist: 'Major Lazer',
      album: 'Lean On (feat. MØ & DJ Snake)',
      genre: 'Pop' },
    { name: 'Got It',
      artist: 'Marian Hill',
      album: 'Sway',
      genre: 'Pop' },
    { name: 'Can You Blame Me',
      artist: 'Matt and Kim',
      album: 'Can You Blame Me',
      genre: 'Pop' },
    { name: 'Talk About You',
      artist: 'MIKA',
      album: 'Talk About You',
      genre: 'Pop' },
    { name: 'Love Like Mine',
      artist: 'Miami Horror',
      album: 'Love Like Mine',
      genre: 'Pop' },
    { name: 'Our Own House',
      artist: 'MisterWives',
      album: 'Our Own House',
      genre: 'Pop' },
    { name: 'The Rhythm',
      artist: 'MNEK',
      album: 'The Rhythm',
      genre: 'Pop' },
    { name: 'Magic (feat. Nile Rodgers and Brandy)',
      artist: 'Mystery Skulls',
      album: 'Forever',
      genre: 'Pop' },
    { name: 'Never Gets Old',
      artist: 'Penguin Prison',
      album: 'Never Gets Old',
      genre: 'Pop' },
    { name: 'Karaoke',
      artist: 'Smallpools',
      album: 'Karaoke',
      genre: 'Pop' },
    { name: 'Robot Love',
      artist: 'Urban Cone',
      album: 'Robot Love',
      genre: 'Pop' },
    { name: 'King',
      artist: 'Years & Years',
      album: 'King',
      genre: 'Pop' },
    { name: 'So Cruel',
      artist: 'Young Empires',
      album: 'So Cruel',
      genre: 'Pop' },
    { name: 'The Night Is Still Young',
      artist: 'Nicki Minaj',
      album: 'The Pinkprint',
      genre: 'Pop' },
    { name: 'I Will Never Let You Down',
      artist: 'Rita Ora',
      album: 'I Will Never Let You Down',
      genre: 'Pop' },
    { name: 'Never Been In Love (feat. Icona Pop)',
      artist: 'Cobra Starship',
      album: 'Never Been In Love (feat. Icona Pop)',
      genre: 'Pop' },
    { name: 'What I did for Love (feat. Emeli Sandé)',
      artist: 'David Guetta',
      album: 'Listen (Deluxe)',
      genre: 'Pop' },
    { name: 'Want To Want Me',
      artist: 'Jason Derulo',
      album: 'Want To Want Me',
      genre: 'Pop' },
    { name: 'Iron Man',
      artist: 'Black Sabbath',
      album: 'Paranoid',
      genre: 'Metal' },
    { name: 'Stronger',
      artist: 'Clean Bandit',
      album: 'New Eyes',
      genre: 'Rock' },
    { name: 'Stole the Show',
      artist: 'Kygo',
      album: 'Stole the Show',
      genre: 'Jazz' },
    { name: 'In Your Arms',
      artist: 'Nico & Vinz',
      album: 'Black Star Elephant',
      genre: 'Folk' },
    { name: 'Intoxicated',
      artist: 'Martin Solveig',
      album: 'Intoxicated (Radio Edit)',
      genre: 'Indie' },
    { name: 'Runaway (U & I)',
      artist: 'Galantis',
      album: 'Runaway (U & I)',
      genre: 'Pop' },
    { name: 'Outside',
      artist: 'Calvin Harris',
      album: 'Motion',
      genre: 'Pop' },
    { name: 'Crazy For You',
      artist: 'Hedley',
      album: 'Wild Life',
      genre: 'Pop' },
    { name: 'Kathleen',
      artist: 'Catfish and the Bottlemen',
      album: 'The Balcony',
      genre: 'Pop' },
    { name: 'Work This Body',
      artist: 'Walk the Moon',
      album: 'TALKING IS HARD',
      genre: 'Pop' },
    { name: 'Seeing Stars',
      artist: 'BØRNS',
      album: 'Candy',
      genre: 'Pop' },
    { name: 'If It\'s Not You',
      artist: 'Keljet',
      album: 'Keljet x AYER - If It\'s Not You',
      genre: 'Pop' },
    { name: 'The Nights',
      artist: 'Avicii',
      album: 'The Days / Nights',
      genre: 'Pop' },
    { name: 'Pay No Mind',
      artist: 'Madeon',
      album: 'Adventure (Deluxe)',
      genre: 'Pop' },
    { name: 'Best Fake Smile',
      artist: 'James Bay',
      album: 'Chaos And The Calm',
      genre: 'Pop' },
    { name: 'Savages',
      artist: 'Marina and The Diamonds',
      album: 'FROOT',
      genre: 'Pop' },
    { name: 'Human Contact',
      artist: 'Catey Shaw',
      album: 'The Brooklyn EP',
      genre: 'Pop' },
    { name: 'Hum Hum',
      artist: 'Mating Ritual',
      album: 'Hum Hum',
      genre: 'Pop' },
    { name: 'Cold Cold Man',
      artist: 'Saint Motel',
      album: 'My Type EP',
      genre: 'Pop' }
  ],
  contacts: [{
    firstName: 'Tony',
    lastName: 'Stark',
    nickName: 'Iron Man',
    emails: [{label: 'work', value: {label: 'contact', value: 'Tony Stark'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Tony Stark'}}]
  }, {
    firstName: 'Donald',
    lastName: 'Blake',
    nickName: 'Thor',
    emails: [{label: 'work', value: {label: 'contact', value: 'Donald Blake'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Donald Blake'}}]
  }, {
    firstName: 'Henry',
    lastName: 'Pym',
    nickName: 'Ant Man',
    emails: [{label: 'work', value: {label: 'contact', value: 'Henry Pym'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Henry Pym'}}]
  }, {
    firstName: 'Bruce',
    lastName: 'Banner',
    nickName: 'Hulk',
    emails: [{label: 'work', value: {label: 'contact', value: 'Bruce Banner'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Bruce Banner'}}]
  }, {
    firstName: 'Steve',
    lastName: 'Rogers',
    nickName: 'Captian America',
    emails: [{label: 'work', value: {label: 'contact', value: 'Steve Rogers'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Steve Rogers'}}]
  }, {
    firstName: 'Clinton',
    lastName: 'Barton',
    nickName: 'Hawkeye',
    emails: [{label: 'work', value: {label: 'contact', value: 'Clinton Barton'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Clinton Barton'}}]
  }, {
    firstName: 'Wanda',
    lastName: 'Maximoff',
    nickName: 'Scarlet Witch',
    emails: [{label: 'work', value: {label: 'contact', value: 'Wanda Maximoff'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Wanda Maximoff'}}]
  }, {
    firstName: 'Victor',
    lastName: 'Shade',
    nickName: 'Vision',
    emails: [{label: 'work', value: {label: 'contact', value: 'Victor Shade'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Victor Shade'}}]
  }, {
    firstName: 'Natalia',
    lastName: 'Romanova',
    nickName: 'Black Widow',
    emails: [{label: 'mobile', value: {label: 'contact', value: 'Natalia Romanova'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Natalia Romanova'}}]
  }, {
    firstName: 'Jennifer',
    lastName: 'Walters',
    nickName: 'She-Hulk',
    emails: [{label: 'work', value: {label: 'contact', value: 'Jennifer Walters'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Jennifer Walters'}}]
  }, {
    firstName: 'Hank',
    lastName: 'McCoy',
    nickName: 'Beast',
    emails: [{label: 'work', value: {label: 'contact', value: 'Hank McCoy'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Hank McCoy'}}]
  }, {
    firstName: 'Peter',
    lastName: 'Quill',
    nickName: 'Starlord',
    emails: [{label: 'work', value: {label: 'contact', value: 'Peter Quill'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Peter Quill'}}]
  }, {
    firstName: 'Reed',
    lastName: 'Richards',
    nickName: 'Mr. Fantastic',
    emails: [{label: 'work', value: {label: 'contact', value: 'Reed Richards'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Reed Richards'}}]
  }, {
    firstName: 'Susan',
    lastName: 'Richards',
    nickName: 'Invisible Woman',
    emails: [{label: 'work', value: {label: 'contact', value: 'Susan Richards'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Susan Richards'}}]
  }, {
    firstName: 'Jim',
    lastName: 'Hammond',
    nickName: 'Human Torch',
    emails: [{label: 'work', value: {label: 'contact', value: 'Jim Hammond'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Jim Hammond'}}]
  }, {
    firstName: 'Benjamin',
    lastName: 'Grimm',
    nickName: 'Thing',
    emails: [{label: 'work', value: {label: 'contact', value: 'Benjamin Grimm'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Benjamin Grimm'}}]
  }, {
    firstName: 'Peter',
    lastName: 'Parker',
    nickName: 'Spiderman',
    emails: [{label: 'work', value: {label: 'contact', value: 'Peter Parker'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Peter Parker'}}]
  }, {
    firstName: 'Luke',
    lastName: 'Cage',
    emails: [{label: 'work', value: {label: 'contact', value: 'Luke Cage'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Luke Cage'}}]
  }, {
    firstName: 'Logan',
    lastName: 'Howlett',
    nickName: 'Wolverine',
    emails: [{label: 'work', value: {label: 'contact', value: 'Logan Howlett'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Logan Howlett'}}]
  }, {
    firstName: 'James',
    lastName: 'Barnes',
    nickName: 'Bucky',
    emails: [{label: 'work', value: {label: 'contact', value: 'James Barnes'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'James Barnes'}}]
  }, {
    firstName: 'Steven',
    lastName: 'Strange',
    emails: [{label: 'work', value: {label: 'contact', value: 'Steven Strange'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Steven Strange'}}]
  }, {
    firstName: 'Matt',
    lastName: 'Murdock',
    nickName: 'Daredevil',
    emails: [{label: 'work', value: {label: 'contact', value: 'Matt Murdock'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Matt Murdock'}}]
  }, {
    firstName: 'Scott',
    lastName: 'Summers',
    nickName: 'Cyclops',
    emails: [{label: 'work', value: {label: 'contact', value: 'Scott Summers'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Scott Summers'}}]
  }, {
    firstName: 'Charles',
    lastName: 'Xavier',
    nickName: 'Professor X',
    emails: [{label: 'work', value: {label: 'contact', value: 'Charles Xavier'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Charles Xavier'}}]
  }, {
    firstName: 'Bobby',
    lastName: 'Drake',
    nickName: 'Iceman',
    emails: [{label: 'work', value: {label: 'contact', value: 'Bobby Drake'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Bobby Drake'}}]
  }, {
    firstName: 'Jean',
    lastName: 'Grey-Summers',
    nickName: 'Phoenix',
    emails: [{label: 'work', work: {label: 'contact', value: 'Jean Grey-Summers'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Jean Grey-Summers'}}]
  }, {
    firstName: 'Kurt',
    lastName: 'Wagner',
    nickName: 'Nightcrawler',
    emails: [{label: 'work', value: {label: 'contact', value: 'Kurt Wagner'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Kurt Wagner'}}]
  }, {
    firstName: 'Ororo',
    lastName: 'Monroe',
    nickName: 'Storm',
    emails: [{label: 'work', value: {label: 'contact', value: 'Ororo Monroe'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Ororo Monroe'}}]
  }, {
    firstName: 'Anna',
    lastName: 'Marie',
    nickName: 'Rogue',
    emails: [{label: 'work', value: {label: 'contact', value: 'Anna Marie'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Anna Marie'}}]
  }, {
    firstName: 'Erik',
    lastName: 'Lehnsherr',
    nickName: 'Magneto',
    emails: [{label: 'work', value: {label: 'contact', value: 'Erik Lehnsherr'}}],
    dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
    phoneNumbers: [{label: 'mobile', value: {label: 'contact', value: 'Erik Lehnsherr'}}]
  }],
  userContact: {
    dates: [
      {label: '_$!<Birthday>!$_', value: {month: 9, day: 11}},
      {label: '_$!<Anniversary>!$_', value: {month: 9, day: 11}}
    ],
    relationships: [{
      label: '_$!<Mother>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your mother'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your mother'}}]
      }
    }, {
      label: '_$!<Brother>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your brother'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your brother'}}]
      }
    }, {
      label: 'husband',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your husband'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your husband'}}]
      }
    }, {
      label: 'wife',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your wife'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your wife'}}]
      }
    }, {
      label: '_$!<Father>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your father'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your father'}}]
      }
    }, {
      label: '_$!<Partner>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your partner'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your partner'}}]
      }
    }, {
      label: '_$!<Sister>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your sister'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your sister'}}]
      }
    }, {
      label: '_$!<Assistant>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your assistant'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your assistant'}}]
      }
    }, {
      label: '_$!<Manager>!$_',
      value: {
        phoneNumbers: [{label: 'mobile', value: {label: 'relationship', value: 'your manager'}}],
        dates: [{label: '_$!<Birthday>!$_', value: {month: 9, day: 11}}],
        emails: [{label: 'work', value: {label: 'relationship', value: 'your manager'}}]
      }
    }]
  },
  volumes: [
    {name: 'Lacona.dmg', canEject: true, canOpen: true, path: 'Lacona.dmg'},
    {name: 'Alfred.dmg', canEject: true, canOpen: true, path: 'Alfred.dmg'},
    {name: 'CD Drive', canEject: true, canOpen: true, path: 'CD Drive'}
  ],
  usHolidays: [
    {text: 'New Years Day', value: new Date(2016, 0, 1)},
    {text: 'Martin Luther King Jr. Day', value: new Date(2016, 0, 18)},
    {text: 'Martin Luther King Day', value: new Date(2016, 0, 18)},
    {text: 'Dr. Martin Luther King Jr. Day', value: new Date(2016, 0, 18)},
    {text: 'Dr. Martin Luther King Day', value: new Date(2016, 0, 18)},
    {text: 'Valentines Day', value: new Date(2016, 1, 14)},
    {text: "Washington's Birthday", value: new Date(2016, 1, 15)},
    {text: 'Presidents Day', value: new Date(2016, 1, 15)},
    {text: 'Memorial Day', value: new Date(2016, 4, 30)},
    {text: 'Independence Day', value: new Date(2016, 6, 4)},
    {text: 'The Fourth of July', value: new Date(2016, 6, 4)},
    {text: 'Labor Day', value: new Date(2015, 8, 7)},
    {text: 'Columbus Day', value: new Date(2015, 9, 12)},
    {text: 'Christopher Columbus Day', value: new Date(2015, 9, 12)},
    {text: 'American Indian Day', value: new Date(2015, 9, 12)},
    {text: 'Native American Day', value: new Date(2015, 9, 12)},
    {text: "Indigenous People's Day ", value: new Date(2015, 9, 12)},
    {text: 'Veterans Day', value: new Date(2015, 10, 11)},
    {text: 'Thanksgiving Day', value: new Date(2015, 10, 26)},
    {text: 'Christmas Eve', value: new Date(2015, 11, 24)},
    {text: 'Christmas Day', value: new Date(2015, 11, 25)},
    {text: 'New Years Eve', value: new Date(2015, 11, 31)}
  ],
  applications: [
    {name: 'Calendar', activationPolicy: 'regular'},
    {name: 'Contacts', activationPolicy: 'regular'},
    {name: 'FaceTime', activationPolicy: 'regular'},
    {name: 'Finder', activationPolicy: 'regular'},
    {name: 'Game Center', activationPolicy: 'regular'},
    {name: 'GarageBand', activationPolicy: 'regular'},
    {name: 'iBooks', activationPolicy: 'regular'},
    {name: 'iMovie', activationPolicy: 'regular'},
    {name: 'iPhoto', activationPolicy: 'regular'},
    {name: 'iTunes', activationPolicy: 'regular'},
    {name: 'Keynote', activationPolicy: 'regular'},
    {name: 'App Store', activationPolicy: 'regular'},
    {name: 'Mail', activationPolicy: 'regular'},
    {name: 'Maps', activationPolicy: 'regular'},
    {name: 'Messages', activationPolicy: 'regular'},
    {name: 'Notes', activationPolicy: 'regular'},
    {name: 'Numbers', activationPolicy: 'regular'},
    {name: 'Pages', activationPolicy: 'regular'},
    {name: 'Photo Booth', activationPolicy: 'regular'},
    {name: 'Reminders', activationPolicy: 'regular'},
    {name: 'Safari', activationPolicy: 'regular'},
    {name: 'Google Chrome', activationPolicy: 'regular'},
    {name: 'Firefox', activationPolicy: 'regular'},
    {name: 'Automator', activationPolicy: 'regular'},
    {name: 'Calculator', activationPolicy: 'regular'},
    {name: 'Chess', activationPolicy: 'regular'},
    {name: 'Dictionary', activationPolicy: 'regular'},
    {name: 'DVD Player', activationPolicy: 'regular'},
    {name: 'Font Book', activationPolicy: 'regular'},
    {name: 'Image Capture', activationPolicy: 'regular'},
    {name: 'Preview', activationPolicy: 'regular'},
    {name: 'QuickTime Player', activationPolicy: 'regular'},
    {name: 'Stickies', activationPolicy: 'accessory'},
    {name: 'System Information', activationPolicy: 'regular'},
    {name: 'TextEdit', activationPolicy: 'regular'},
    {name: 'VoiceOver Utility', activationPolicy: 'accessory'}
  ],
  bookmarks: [
    {name: 'Facebook', url:'http://facebook.com'},
    {name: 'Twitter', url:'http://twitter.com'},
    {name: 'Google', url:'http://google.com'},
    {name: 'Lifehacker', url:'http://lifehacker.com'},
    {name: 'xkcd', url:'http://xkcd.com'},
    {name: 'Github', url:'http://github.com'},
    {name: 'Gmail', url:'http://gmail.com'},
    {name: 'Youtube', url:'http://youtube.com'},
    {name: 'Wikipedia', url:'http://wikipedia.org'},
    {name: 'Ebay', url:'http://ebay.com'}
  ],
  preferencePanes: [
    {name: 'Displays', path: 'Displays'},
    {name: 'Desktop & Screen Saver', path: 'Desktop & Screen Saver'},
    {name: 'Extensions', path: 'Extensions'},
    {name: 'Energy Saver', path: 'Energy Saver'},
    {name: 'Sound', path: 'Sound'},
    {name: 'Keyboard', path: 'Keyboard'},
    {name: 'Internet Accounts', path: 'Internet Accounts'},
    {name: 'Date & Time', path: 'Date & Time'},
    {name: 'Accessibility', path: 'Accessibility'},
    {name: 'Security & Privacy', path: 'Security & Privacy'},
    {name: 'Dock', path: 'Dock'},
    {name: 'Profiles', path: 'Profiles'},
    {name: 'Network', path: 'Network'},
    {name: 'Notifications', path: 'Notifications'},
    {name: 'Fibre Channel', path: 'Fibre Channel'},
    {name: 'App Store', path: 'App Store'},
    {name: 'Time Machine', path: 'Time Machine'},
    {name: 'General', path: 'General'},
    {name: 'Dictation & Speech', path: 'Dictation & Speech'},
    {name: 'Spotlight', path: 'Spotlight'},
    {name: 'Ink', path: 'Ink'},
    {name: 'Language & Region', path: 'Language & Region'},
    {name: 'CDs & DVDs', path: 'CDs & DVDs'},
    {name: 'Sharing', path: 'Sharing'},
    {name: 'Users & Groups', path: 'Users & Groups'},
    {name: 'Bluetooth', path: 'Bluetooth'},
    {name: 'Mouse', path: 'Mouse'},
    {name: 'Trackpad', path: 'Trackpad'},
    {name: 'Mission Control', path: 'Mission Control'},
    {name: 'Startup Disk', path: 'Startup Disk'},
    {name: 'Parental Controls', path: 'Parental Controls'},
    {name: 'Printers & Scanners', path: 'Printers & Scanners'},
    {name: 'iCloud', path: 'iCloud'}
  ],
  spotlightFiles: [
    {path: '/Users/LaconaUser/Documents/log.csv'},
    {path: '/Users/LaconaUser/Documents/lacona-logo.png'},
    {path: '/Users/LaconaUser/Documents/kickstarter-video.m4v'},
    {path: '/Users/LaconaUser/Documents/document.docx'},
    {path: '/Users/LaconaUser/Documents/my-document.docx'},
    {path: '/Users/LaconaUser/Projects/test/main.js'},
    {path: '/Users/LaconaUser/Projects/test/package.json'},
    {path: '/Users/LaconaUser/Projects/test/lodash.js'},
    {path: '/Users/LaconaUser/Projects/test/react-router.jsx'},
    {path: '/Users/LaconaUser/Documents/Presentations/briefing 1_2.keynote'},
    {path: '/Users/LaconaUser/Documents/Presentations/briefing 2_24.keynote'},
    {path: '/Users/LaconaUser/Documents/Presentations/briefing 5_5.keynote'},
    {path: '/Users/LaconaUser/status-updates.txt'},
    {path: '/Users/LaconaUser/todo.txt'},
    {path: '/Users/LaconaUser/Projects/cpp-test/main.cpp'},
    {path: '/Users/LaconaUser/Projects/cpp-test/main.h'},
    {path: '/Users/LaconaUser/Projects/cpp-test/quick-brown-fox.js'},
    {path: '/Users/LaconaUser/Projects/cpp-test/overjumper.cs'},
    {path: '/Users/LaconaUser/Projects/cpp-test/overjumper.h'},
    {path: '/Users/LaconaUser/Projects/cpp-test/lazy_dog.js'}
  ],
  rootFiles:
  { '/':
   [ { file: 'Applications', isDir: true },
     { file: 'Library', isDir: true },
     { file: 'Users', isDir: true },
     { file: 'bin', isDir: true },
     { file: 'etc', isDir: true },
     { file: 'home', isDir: true },
     { file: 'net', isDir: true },
     { file: 'tmp', isDir: true },
     { file: 'usr', isDir: true },
     { file: 'var', isDir: true } ],
  '/Applications/':
   [ { file: 'App Store.app', isDir: true },
     { file: 'Atom.app', isDir: true },
     { file: 'Automator.app', isDir: true },
     { file: 'Calculator.app', isDir: true },
     { file: 'Calendar.app', isDir: true },
     { file: 'Chess.app', isDir: true },
     { file: 'Contacts.app', isDir: true },
     { file: 'DVD Player.app', isDir: true },
     { file: 'Dash.app', isDir: true },
     { file: 'Dashboard.app', isDir: true },
     { file: 'Dictionary.app', isDir: true },
     { file: 'FaceTime.app', isDir: true },
     { file: 'Font Book.app', isDir: true },
     { file: 'Game Center.app', isDir: true },
     { file: 'GarageBand.app', isDir: true },
     { file: 'GitHub.app', isDir: true },
     { file: 'Google Chrome.app', isDir: true },
     { file: 'Image Capture.app', isDir: true },
     { file: 'Keynote.app', isDir: true },
     { file: 'Launchpad.app', isDir: true },
     { file: 'Mail.app', isDir: true },
     { file: 'Maps.app', isDir: true },
     { file: 'Messages.app', isDir: true },
     { file: 'Mission Control.app', isDir: true },
     { file: 'Notes.app', isDir: true },
     { file: 'Numbers.app', isDir: true },
     { file: 'Pages.app', isDir: true },
     { file: 'Photo Booth.app', isDir: true },
     { file: 'Photos.app', isDir: true },
     { file: 'Preview.app', isDir: true },
     { file: 'QuickTime Player.app', isDir: true },
     { file: 'Reminders.app', isDir: true },
     { file: 'Safari.app', isDir: true },
     { file: 'Slack.app', isDir: true },
     { file: 'Stickies.app', isDir: true },
     { file: 'System Preferences.app', isDir: true },
     { file: 'TextEdit.app', isDir: true },
     { file: 'Time Machine.app', isDir: true },
     { file: 'Utilities', isDir: true },
     { file: 'Xcode.app', isDir: true },
     { file: 'iBooks.app', isDir: true },
     { file: 'iMovie.app', isDir: true },
     { file: 'iPhoto.app', isDir: true },
     { file: 'iTunes.app', isDir: true } ],
  '/Applications/App Store.app/': [ { file: '...', isDir: false } ],
  '/Applications/Atom.app/': [ { file: '...', isDir: false } ],
  '/Applications/Automator.app/': [ { file: '...', isDir: false } ],
  '/Applications/Calculator.app/': [ { file: '...', isDir: false } ],
  '/Applications/Calendar.app/': [ { file: '...', isDir: false } ],
  '/Applications/Chess.app/': [ { file: '...', isDir: false } ],
  '/Applications/Contacts.app/': [ { file: '...', isDir: false } ],
  '/Applications/DVD Player.app/': [ { file: '...', isDir: false } ],
  '/Applications/Dash.app/': [ { file: '...', isDir: false } ],
  '/Applications/Dashboard.app/': [ { file: '...', isDir: false } ],
  '/Applications/Dictionary.app/': [ { file: '...', isDir: false } ],
  '/Applications/FaceTime.app/': [ { file: '...', isDir: false } ],
  '/Applications/Font Book.app/': [ { file: '...', isDir: false } ],
  '/Applications/Game Center.app/': [ { file: '...', isDir: false } ],
  '/Applications/GarageBand.app/': [ { file: '...', isDir: false } ],
  '/Applications/GitHub.app/': [ { file: '...', isDir: false } ],
  '/Applications/Google Chrome.app/': [ { file: '...', isDir: false } ],
  '/Applications/Image Capture.app/': [ { file: '...', isDir: false } ],
  '/Applications/Keynote.app/': [ { file: '...', isDir: false } ],
  '/Applications/Launchpad.app/': [ { file: '...', isDir: false } ],
  '/Applications/Mail.app/': [ { file: '...', isDir: false } ],
  '/Applications/Maps.app/': [ { file: '...', isDir: false } ],
  '/Applications/Messages.app/': [ { file: '...', isDir: false } ],
  '/Applications/Mission Control.app/': [ { file: '...', isDir: false } ],
  '/Applications/Notes.app/': [ { file: '...', isDir: false } ],
  '/Applications/Numbers.app/': [ { file: '...', isDir: false } ],
  '/Applications/Pages.app/': [ { file: '...', isDir: false } ],
  '/Applications/Photo Booth.app/': [ { file: '...', isDir: false } ],
  '/Applications/Photos.app/': [ { file: '...', isDir: false } ],
  '/Applications/Preview.app/': [ { file: '...', isDir: false } ],
  '/Applications/QuickTime Player.app/': [ { file: '...', isDir: false } ],
  '/Applications/Reminders.app/': [ { file: '...', isDir: false } ],
  '/Applications/Safari.app/': [ { file: '...', isDir: false } ],
  '/Applications/Slack.app/': [ { file: '...', isDir: false } ],
  '/Applications/Stickies.app/': [ { file: '...', isDir: false } ],
  '/Applications/System Preferences.app/': [ { file: '...', isDir: false } ],
  '/Applications/TextEdit.app/': [ { file: '...', isDir: false } ],
  '/Applications/Time Machine.app/': [ { file: '...', isDir: false } ],
  '/Applications/Utilities/': [ { file: '...', isDir: false } ],
  '/Applications/Xcode.app/': [ { file: '...', isDir: false } ],
  '/Applications/iBooks.app/': [ { file: '...', isDir: false } ],
  '/Applications/iMovie.app/': [ { file: '...', isDir: false } ],
  '/Applications/iPhoto.app/': [ { file: '...', isDir: false } ],
  '/Applications/iTunes.app/': [ { file: '...', isDir: false } ],
  '/Library/':
   [ { file: 'Application Support', isDir: true },
     { file: 'Audio', isDir: true },
     { file: 'Caches', isDir: true },
     { file: 'ColorPickers', isDir: true },
     { file: 'ColorSync', isDir: true },
     { file: 'Components', isDir: true },
     { file: 'Compositions', isDir: true },
     { file: 'Contextual Menu Items', isDir: true },
     { file: 'CoreMediaIO', isDir: true },
     { file: 'Desktop Pictures', isDir: true },
     { file: 'Developer', isDir: true },
     { file: 'Dictionaries', isDir: true },
     { file: 'DirectoryServices', isDir: true },
     { file: 'Documentation', isDir: true },
     { file: 'DropboxHelperTools', isDir: true },
     { file: 'Extensions', isDir: true },
     { file: 'Filesystems', isDir: true },
     { file: 'Fonts', isDir: true },
     { file: 'Frameworks', isDir: true },
     { file: 'Google', isDir: true },
     { file: 'Graphics', isDir: true },
     { file: 'Image Capture', isDir: true },
     { file: 'Input Methods', isDir: true },
     { file: 'Internet Plug-Ins', isDir: true },
     { file: 'Java', isDir: true },
     { file: 'Keyboard Layouts', isDir: true },
     { file: 'Keychains', isDir: true },
     { file: 'LaunchAgents', isDir: true },
     { file: 'LaunchDaemons', isDir: true },
     { file: 'Logs', isDir: true },
     { file: 'Messages', isDir: true },
     { file: 'Modem Scripts', isDir: true },
     { file: 'OpenDirectory', isDir: true },
     { file: 'PDF Services', isDir: true },
     { file: 'Perl', isDir: true },
     { file: 'PreferencePanes', isDir: true },
     { file: 'Preferences', isDir: true },
     { file: 'Printers', isDir: true },
     { file: 'PrivilegedHelperTools', isDir: true },
     { file: 'Python', isDir: true },
     { file: 'QuickLook', isDir: true },
     { file: 'QuickTime', isDir: true },
     { file: 'Receipts', isDir: true },
     { file: 'Ruby', isDir: true },
     { file: 'Sandbox', isDir: true },
     { file: 'Screen Savers', isDir: true },
     { file: 'ScriptingAdditions', isDir: true },
     { file: 'Scripts', isDir: true },
     { file: 'Security', isDir: true },
     { file: 'Server', isDir: true },
     { file: 'Speech', isDir: true },
     { file: 'Spelling', isDir: true },
     { file: 'Spotlight', isDir: true },
     { file: 'StartupItems', isDir: true },
     { file: 'SystemMigration', isDir: true },
     { file: 'SystemProfiler', isDir: true },
     { file: 'Updates', isDir: true },
     { file: 'User Pictures', isDir: true },
     { file: 'Video', isDir: true },
     { file: 'WebServer', isDir: true },
     { file: 'Widgets', isDir: true },
     { file: 'iTunes', isDir: true } ],
  '/Library/Application Support/': [ { file: '...', isDir: false } ],
  '/Library/Audio/': [ { file: '...', isDir: false } ],
  '/Library/Caches/': [ { file: '...', isDir: false } ],
  '/Library/ColorPickers/': [ { file: '...', isDir: false } ],
  '/Library/ColorSync/': [ { file: '...', isDir: false } ],
  '/Library/Components/': [ { file: '...', isDir: false } ],
  '/Library/Compositions/': [ { file: '...', isDir: false } ],
  '/Library/Contextual Menu Items/': [ { file: '...', isDir: false } ],
  '/Library/CoreMediaIO/': [ { file: '...', isDir: false } ],
  '/Library/Desktop Pictures/': [ { file: '...', isDir: false } ],
  '/Library/Developer/': [ { file: '...', isDir: false } ],
  '/Library/Dictionaries/': [ { file: '...', isDir: false } ],
  '/Library/DirectoryServices/': [ { file: '...', isDir: false } ],
  '/Library/Documentation/': [ { file: '...', isDir: false } ],
  '/Library/DropboxHelperTools/': [ { file: '...', isDir: false } ],
  '/Library/Extensions/': [ { file: '...', isDir: false } ],
  '/Library/Filesystems/': [ { file: '...', isDir: false } ],
  '/Library/Fonts/': [ { file: '...', isDir: false } ],
  '/Library/Frameworks/': [ { file: '...', isDir: false } ],
  '/Library/Google/': [ { file: '...', isDir: false } ],
  '/Library/Graphics/': [ { file: '...', isDir: false } ],
  '/Library/Image Capture/': [ { file: '...', isDir: false } ],
  '/Library/Input Methods/': [ { file: '...', isDir: false } ],
  '/Library/Internet Plug-Ins/': [ { file: '...', isDir: false } ],
  '/Library/Java/': [ { file: '...', isDir: false } ],
  '/Library/Keyboard Layouts/': [ { file: '...', isDir: false } ],
  '/Library/Keychains/': [ { file: '...', isDir: false } ],
  '/Library/LaunchAgents/': [ { file: '...', isDir: false } ],
  '/Library/LaunchDaemons/': [ { file: '...', isDir: false } ],
  '/Library/Logs/': [ { file: '...', isDir: false } ],
  '/Library/Messages/': [ { file: '...', isDir: false } ],
  '/Library/Modem Scripts/': [ { file: '...', isDir: false } ],
  '/Library/OpenDirectory/': [ { file: '...', isDir: false } ],
  '/Library/PDF Services/': [ { file: '...', isDir: false } ],
  '/Library/Perl/': [ { file: '...', isDir: false } ],
  '/Library/PreferencePanes/': [ { file: '...', isDir: false } ],
  '/Library/Preferences/': [ { file: '...', isDir: false } ],
  '/Library/Printers/': [ { file: '...', isDir: false } ],
  '/Library/PrivilegedHelperTools/': [ { file: '...', isDir: false } ],
  '/Library/Python/': [ { file: '...', isDir: false } ],
  '/Library/QuickLook/': [ { file: '...', isDir: false } ],
  '/Library/QuickTime/': [ { file: '...', isDir: false } ],
  '/Library/Receipts/': [ { file: '...', isDir: false } ],
  '/Library/Ruby/': [ { file: '...', isDir: false } ],
  '/Library/Sandbox/': [ { file: '...', isDir: false } ],
  '/Library/Screen Savers/': [ { file: '...', isDir: false } ],
  '/Library/ScriptingAdditions/': [ { file: '...', isDir: false } ],
  '/Library/Scripts/': [ { file: '...', isDir: false } ],
  '/Library/Security/': [ { file: '...', isDir: false } ],
  '/Library/Server/': [ { file: '...', isDir: false } ],
  '/Library/Speech/': [ { file: '...', isDir: false } ],
  '/Library/Spelling/': [ { file: '...', isDir: false } ],
  '/Library/Spotlight/': [ { file: '...', isDir: false } ],
  '/Library/StartupItems/': [ { file: '...', isDir: false } ],
  '/Library/SystemMigration/': [ { file: '...', isDir: false } ],
  '/Library/SystemProfiler/': [ { file: '...', isDir: false } ],
  '/Library/Updates/': [ { file: '...', isDir: false } ],
  '/Library/User Pictures/': [ { file: '...', isDir: false } ],
  '/Library/Video/': [ { file: '...', isDir: false } ],
  '/Library/WebServer/': [ { file: '...', isDir: false } ],
  '/Library/Widgets/': [ { file: '...', isDir: false } ],
  '/Library/iTunes/': [ { file: '...', isDir: false } ],
  '/Users/':
   [ { file: 'LaconaUser', isDir: true },
     { file: 'Guest', isDir: true },
     { file: 'Shared', isDir: true } ],
  '/Users/LaconaUser/':
   [ { file: 'Desktop', isDir: true },
     { file: 'Documents', isDir: true },
     { file: 'Downloads', isDir: true },
     { file: 'Library', isDir: true },
     { file: 'Movies', isDir: true },
     { file: 'Music', isDir: true },
     { file: 'Pictures', isDir: true } ],
  '/Users/LaconaUser/Desktop/':
   [ { file: 'mydocument.pages', isDir: false },
     { file: 'mockup.html', isDir: false },
     { file: 'kickstarter.url', isDir: false } ],
  '/Users/LaconaUser/Documents/':
   [ { file: 'University', isDir: true },
     { file: 'Resumes', isDir: true },
     { file: 'Ideas', isDir: true },
     { file: 'Presentations', isDir: true },
     { file: 'Projects', isDir: true },
     { file: 'NLP', isDir: true } ],
  '/Users/LaconaUser/Documents/University/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Documents/Resumes/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Documents/Ideas/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Documents/Presentations/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Documents/Projects/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Documents/NLP/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Downloads/': [ { file: 'Lacona.dmg', isDir: false } ],
  '/Users/LaconaUser/Library/':
   [ { file: 'Accounts', isDir: true },
     { file: 'Application Scripts', isDir: true },
     { file: 'Application Support', isDir: true },
     { file: 'Assistants', isDir: true },
     { file: 'Audio', isDir: true },
     { file: 'Autosave Information', isDir: true },
     { file: 'Caches', isDir: true },
     { file: 'Calendars', isDir: true },
     { file: 'ColorPickers', isDir: true },
     { file: 'Colors', isDir: true },
     { file: 'Compositions', isDir: true },
     { file: 'Containers', isDir: true },
     { file: 'Cookies', isDir: true },
     { file: 'Developer', isDir: true },
     { file: 'Dictionaries', isDir: true },
     { file: 'Favorites', isDir: true },
     { file: 'FlashlightPlugins', isDir: true },
     { file: 'FontCollections', isDir: true },
     { file: 'Fonts', isDir: true },
     { file: 'GameKit', isDir: true },
     { file: 'Google', isDir: true },
     { file: 'Group Containers', isDir: true },
     { file: 'IdentityServices', isDir: true },
     { file: 'Input Methods', isDir: true },
     { file: 'Internet Plug-Ins', isDir: true },
     { file: 'Keyboard Layouts', isDir: true },
     { file: 'Keychains', isDir: true },
     { file: 'LanguageModeling', isDir: true },
     { file: 'LaunchAgents', isDir: true },
     { file: 'Logs', isDir: true },
     { file: 'Mail', isDir: true },
     { file: 'Messages', isDir: true },
     { file: 'Mobile Documents', isDir: true },
     { file: 'PreferencePanes', isDir: true },
     { file: 'Preferences', isDir: true },
     { file: 'Printers', isDir: true },
     { file: 'PubSub', isDir: true },
     { file: 'Safari', isDir: true },
     { file: 'Saved Application State', isDir: true },
     { file: 'Saved Searches', isDir: true },
     { file: 'Screen Savers', isDir: true },
     { file: 'ScriptingAdditions', isDir: true },
     { file: 'Services', isDir: true },
     { file: 'Sounds', isDir: true },
     { file: 'Spelling', isDir: true },
     { file: 'SyncedPreferences', isDir: true },
     { file: 'Voices', isDir: true },
     { file: 'WebKit', isDir: true },
     { file: 'com.apple.nsurlsessiond', isDir: true },
     { file: 'iMovie', isDir: true },
     { file: 'iTunes', isDir: true } ],
  '/Users/LaconaUser/Library/Accounts/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Application Scripts/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Application Support/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Assistants/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Audio/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Autosave Information/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Caches/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Calendars/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/ColorPickers/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Colors/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Compositions/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Containers/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Cookies/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Developer/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Dictionaries/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Favorites/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/FlashlightPlugins/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/FontCollections/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Fonts/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/GameKit/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Google/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Group Containers/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/IdentityServices/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Input Methods/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Internet Plug-Ins/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Keyboard Layouts/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Keychains/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/LanguageModeling/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/LaunchAgents/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Logs/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Mail/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Messages/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Mobile Documents/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/PreferencePanes/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Preferences/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Printers/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/PubSub/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Safari/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Saved Application State/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Saved Searches/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Screen Savers/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/ScriptingAdditions/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Services/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Sounds/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Spelling/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/SyncedPreferences/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/Voices/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/WebKit/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/com.apple.nsurlsessiond/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/iMovie/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Library/iTunes/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Movies/':
   [ { file: 'The Avengers.avi', isDir: false },
     { file: 'X-Men First Class.avi', isDir: false },
     { file: 'Iron Man.avi', isDir: false } ],
  '/Users/LaconaUser/Music/':
   [ { file: 'Audio Music Apps', isDir: true },
     { file: 'GarageBand', isDir: true },
     { file: 'iTunes', isDir: true } ],
  '/Users/LaconaUser/Music/Audio Music Apps/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Music/GarageBand/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Music/iTunes/': [ { file: '...', isDir: false } ],
  '/Users/LaconaUser/Pictures/': [ { file: 'Photos Library.photoslibrary', isDir: false } ],
  '/Users/Guest/': [ { file: '...', isDir: false } ],
  '/Users/Shared/': [ { file: '...', isDir: false } ],
  '/bin/':
   [ { file: 'bash', isDir: false },
     { file: 'cat', isDir: false },
     { file: 'chmod', isDir: false },
     { file: 'cp', isDir: false },
     { file: 'csh', isDir: false },
     { file: 'date', isDir: false },
     { file: 'dd', isDir: false },
     { file: 'df', isDir: false },
     { file: 'domainname', isDir: false },
     { file: 'echo', isDir: false },
     { file: 'ed', isDir: false },
     { file: 'expr', isDir: false },
     { file: 'hostname', isDir: false },
     { file: 'kill', isDir: false },
     { file: 'ksh', isDir: false },
     { file: 'launchctl', isDir: false },
     { file: 'link', isDir: false },
     { file: 'ln', isDir: false },
     { file: 'ls', isDir: false },
     { file: 'mkdir', isDir: false },
     { file: 'mv', isDir: false },
     { file: 'pax', isDir: false },
     { file: 'ps', isDir: false },
     { file: 'pwd', isDir: false },
     { file: 'rcp', isDir: false },
     { file: 'rm', isDir: false },
     { file: 'rmdir', isDir: false },
     { file: 'sh', isDir: false },
     { file: 'sleep', isDir: false },
     { file: 'stty', isDir: false },
     { file: 'sync', isDir: false },
     { file: 'tcsh', isDir: false },
     { file: 'test', isDir: false },
     { file: 'unlink', isDir: false },
     { file: 'wait4path', isDir: false },
     { file: 'zsh', isDir: false } ],
  '/etc/': [],
  '/home/': [],
  '/net/': [],
  '/tmp/':
   [ { file: 'KSOutOfProcessFetcher.0.OlaJUhhgKAnFsX7fZ0FyXTFxIgg=',
       isDir: false },
     { file: 'com.apple.launchd.CWPFO2w3Rj', isDir: false },
     { file: 'com.apple.launchd.eM0bByeRbW', isDir: false },
     { file: 'tmphosts', isDir: false },
     { file: 'tmphosts1', isDir: false },
     { file: 'some.tmp', isDir: false },
     { file: 'test.tmp', isDir: false },
     { file: 'yes.txt', isDir: false } ],
  '/usr/':
   [ { file: 'X11', isDir: true },
     { file: 'X11R6', isDir: true },
     { file: 'bin', isDir: true },
     { file: 'include', isDir: true },
     { file: 'lib', isDir: true },
     { file: 'libexec', isDir: true },
     { file: 'local', isDir: true },
     { file: 'sbin', isDir: true },
     { file: 'share', isDir: true },
     { file: 'standalone', isDir: true } ],
  '/usr/X11/': [ { file: '...', isDir: false } ],
  '/usr/X11R6/': [ { file: '...', isDir: false } ],
  '/usr/bin/': [ { file: '...', isDir: false } ],
  '/usr/include/': [ { file: '...', isDir: false } ],
  '/usr/lib/': [ { file: '...', isDir: false } ],
  '/usr/libexec/': [ { file: '...', isDir: false } ],
  '/usr/local/': [ { file: '...', isDir: false } ],
  '/usr/sbin/': [ { file: '...', isDir: false } ],
  '/usr/share/': [ { file: '...', isDir: false } ],
  '/usr/standalone/': [ { file: '...', isDir: false } ],
  '/var/':
   [ { file: 'Keychains', isDir: true },
     { file: 'agentx', isDir: true },
     { file: 'at', isDir: true },
     { file: 'audit', isDir: true },
     { file: 'backups', isDir: true },
     { file: 'db', isDir: true },
     { file: 'empty', isDir: true },
     { file: 'folders', isDir: true },
     { file: 'folders~orig', isDir: true },
     { file: 'jabberd', isDir: true },
     { file: 'lib', isDir: true },
     { file: 'log', isDir: true },
     { file: 'mail', isDir: true },
     { file: 'msgs', isDir: true },
     { file: 'netboot', isDir: true },
     { file: 'networkd', isDir: true },
     { file: 'root', isDir: true },
     { file: 'rpc', isDir: true },
     { file: 'run', isDir: true },
     { file: 'rwho', isDir: true },
     { file: 'spool', isDir: true },
     { file: 'tmp', isDir: true },
     { file: 'vm', isDir: true },
     { file: 'yp', isDir: true } ],
  '/var/Keychains/': [ { file: '...', isDir: false } ],
  '/var/agentx/': [ { file: '...', isDir: false } ],
  '/var/at/': [ { file: '...', isDir: false } ],
  '/var/audit/': [ { file: '...', isDir: false } ],
  '/var/backups/': [ { file: '...', isDir: false } ],
  '/var/db/': [ { file: '...', isDir: false } ],
  '/var/empty/': [ { file: '...', isDir: false } ],
  '/var/folders/': [ { file: '...', isDir: false } ],
  '/var/folders~orig/': [ { file: '...', isDir: false } ],
  '/var/jabberd/': [ { file: '...', isDir: false } ],
  '/var/lib/': [ { file: '...', isDir: false } ],
  '/var/log/': [ { file: '...', isDir: false } ],
  '/var/mail/': [ { file: '...', isDir: false } ],
  '/var/msgs/': [ { file: '...', isDir: false } ],
  '/var/netboot/': [ { file: '...', isDir: false } ],
  '/var/networkd/': [ { file: '...', isDir: false } ],
  '/var/root/': [ { file: '...', isDir: false } ],
  '/var/rpc/': [ { file: '...', isDir: false } ],
  '/var/run/': [ { file: '...', isDir: false } ],
  '/var/rwho/': [ { file: '...', isDir: false } ],
  '/var/spool/': [ { file: '...', isDir: false } ],
  '/var/tmp/': [ { file: '...', isDir: false } ],
  '/var/vm/': [ { file: '...', isDir: false } ],
  '/var/yp/': [ { file: '...', isDir: false } ] }
}
